---
name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.9
main: FactionsPro\FactionMain
api:
- 2.0.0
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: Allow use of all faction commands
...
